name: Tag Issues and Pull Requests

on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tag-issues-and-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue or PR title
        id: check-title
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: echo "Issue or PR title is $ISSUE_TITLE"

      - name: Add labels based on title
        id: add-labels
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          title_lowercase="$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]')"
          echo "Issue or PR title is $title_lowercase"
          if [[ "$title_lowercase" == *"bug"* ]]; then
            gh issue label "$ISSUE_TITLE" --add bug
          fi
          if [[ "$title_lowercase" == *"dependencies"* ]]; then
            gh issue label "$ISSUE_TITLE" --add dependencies
          fi
          if [[ "$title_lowercase" == *"documentation"* ]]; then
            gh issue label "$ISSUE_TITLE" --add documentation
          fi
          if [[ "$title_lowercase" == *"enhancement"* ]]; then
            gh issue label "$ISSUE_TITLE" --add enhancement
          fi

      - name: Comment on the issue or PR
        if: steps.add-labels.outputs.contains-label == 'true'
        run: echo "Labels added based on title"
